### ISSUE TITLE
[Question] Advantages

### ISSUE THREAD

**Issue by webdesus** [srsudar/SemCache#25]
I understand correct it's like [pocket](https://getpocket.com/) but has next differences:

1.  Only PC
2.  Share local network. (pocket use internet for share)

**Comment by srsudar** [comment]
Yep that's basically right.

1. In its current implementation it is only desktop (and specifically Chrome), but that is only because I haven't created a mobile version. As far as I know there's nothing that would prevent the protocol working with mobile devices.
2. It shares via the local network, and it shares the saved content itself, not a link. I would guess that Pocket shares a link.

An additional difference is that this tool doesn't do any clever manipulations to the page when it is saved. It saves the exact content. Pocket seems to make things prettier. I'm not a heavy pocket user, so there are potentially other differences that I'm forgetting, but your points 1 and 2 are the main ones.

**Comment by webdesus** [comment]
> this tool doesn't do any clever manipulations to the page when it is saved

Wow it's what i wanted, but only for mobile . Sometimes i have big a problem with clever manipulations pocket and i don't have internet for open source. I think you should write on readme about this advantage.

**Comment by webdesus** [comment]
But after send commet i remember about chrome for mobile. Recently google add feature  save pages for offline reading.

**Comment by srsudar** [comment]
Yep they most definitely did. Awesome feature, too!

If you desperately need something on desktop, you can go to `chrome://flags` and enable `Save page as MHTML`. This will allow you to `File | Save` and select the option "Single webpage, complete" or something like that. These mhtml files are can then be opened by Chrome. You'll have to do management yourself, but it effectively snapshots the DOM. That is the storage mechanism I'm using to save pages without any modification.

**Comment by srsudar** [comment]
FYI, finally updated the README about this. Added some screenshots too, but it still won't help you if you're after mobile.
